### ISSUE TITLE
Store display info

### ISSUE THREAD

**Issue by AlecMMiller** [18x18az/maestro#46]
https://github.com/18x18az/maestro/tree/beta/src/features/devices/displays

When displays get registered in the display controller

https://github.com/18x18az/maestro/blob/beta/src/features/devices/displays/displays.controller.ts

the display service just immediately publishes to the relevant topic that it should listen to field 1.

https://github.com/18x18az/maestro/blob/beta/src/features/devices/displays/displays.service.ts

What should happen is there should be a displays.repo.ts that creates an entry in the database with the primary key of the UUID, a string field "name" for a human readable name, and a string field "field" for the field it's associated with. Entries in the database are created at

https://github.com/18x18az/maestro/blob/beta/prisma/schema.prisma

and an example of how a repo works is at

https://github.com/18x18az/maestro/blob/beta/src/features/initial/inspection/repo.service.ts

There should be two new routes in the controller

:uuid/name to set the name

:uuid/assign to set the field it's assigned to

With both routes they should update the relevant entry in the database, with the field assign one it should also broadcast to the relevant topic which field the display is now assigned to

**Comment by meisZWFLZ** [comment]
There's a few things that I'm unsure about/need more context to make the right decision before I can submit a pull request, marked with comments containing `@question`
