### ISSUE TITLE
Add all inspection criteria

### ISSUE THREAD

**Issue by AlecMMiller** [18x18az/maestro#52]
https://github.com/18x18az/maestro/blob/beta/src/features/initial/inspection/consts/baseInspection.ts

currently only has two inspection criteria

Complete list is here

https://roboticseducation.org/documents/2023/05/robot-inspection-checklist-vrc-over-under.pdf/

**Comment by meisZWFLZ** [comment]
script and its output: https://gist.github.com/meisZWFLZ/21b2058c60ecb56b8952f08c99d899f8

The "Total power of motors is limited to 88W equivalence...." requirement is a bit hard to read without newlines, will including newlines break anything?

I'll create the branch and pr tommorow

**Comment by AlecMMiller** [comment]
Including newlines is fine
